### ISSUE TITLE
加载好慢、第一次登录内部错误、第二次账号密码错误

### ISSUE THREAD

**Issue by Tomao2014** [csx-bill/quick-boot#1]
![image](https://user-images.githubusercontent.com/46468204/233889887-361f9ebb-02c3-4237-9d8d-6fc17c34e943.png)

**Comment by csx-bill** [comment]
内网穿透的，是有点慢的，应该是被人改了密码，我处理下

**Comment by Tomao2014** [comment]
![image](https://user-images.githubusercontent.com/46468204/233893336-2f00c588-175e-4182-85c4-65c10649f816.png)
我刚又试了，依旧是账号密码错误。另外，第一次直接通过域名访问，会提示错误。之后重定向到登录页面，可能是路由处理的时候，增加了不必要的弹框

**Comment by csx-bill** [comment]
已修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tomao2014 ***@***.***&gt;
发送时间: 2023年4月24日 11:26
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 加载好慢、第一次登录内部错误、第二次账号密码错误 (Issue #1)





 

 我刚又试了，依旧是账号密码错误。另外，第一次直接通过域名访问，会提示错误。之后重定向到登录页面，可能是路由处理的时候，增加了不必要的弹框

**Comment by csx-bill** [comment]
token 过期忘记处理了，晚点处理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tomao2014 ***@***.***&gt;
发送时间: 2023年4月24日 11:26
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 加载好慢、第一次登录内部错误、第二次账号密码错误 (Issue #1)





 

 我刚又试了，依旧是账号密码错误。另外，第一次直接通过域名访问，会提示错误。之后重定向到登录页面，可能是路由处理的时候，增加了不必要的弹框

**Comment by Tomao2014** [comment]
![image](https://user-images.githubusercontent.com/46468204/234189916-dbe7c57e-1764-4787-ac83-7cbc18476642.png)

没有吧
