### ISSUE TITLE
本地编译不过，少一个依赖

### ISSUE THREAD

**Issue by wubin1989** [csx-bill/quick-boot#11]
[ERROR] Failed to execute goal on project quick-boot-online-biz: Could not resolve dependencies for project com.quick:quick-boot-online-biz:jar:1.0.1: The following artifacts could not be resolved: com.github.csx-bill:APIJSON:jar:30509f10, com.github.csx-bill:apijson-framework:jar:6.3.0_jdk17, com.github.csx-bill:apijson-router:jar:1.8.0_jdk17: Could not find artifact com.github.csx-bill:APIJSON:jar:30509f10 in aliyunmaven (https://maven.aliyun.com/repository/public)

**Comment by csx-bill** [comment]
apijson  的依赖 在 https://jitpack.io 应该是没有拉取到

**Comment by wubin1989** [comment]
后端完全没法跑啊。apijson的依赖都是分散的，得一个个想办法。上手成本太高了吧

**Comment by wubin1989** [comment]
不是驴不走就是磨不转

**Comment by csx-bill** [comment]
不存在依赖缺失问题
