### ISSUE TITLE
站点不存在

### ISSUE THREAD

**Issue by Mengleijin** [csx-bill/quick-boot#3]
hello，访问演示站点，提示站点不存在？

**Comment by csx-bill** [comment]
演示站点暂时挂了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Menglei Jin ***@***.***&gt;
发送时间: 2023年5月29日 17:18
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 站点不存在 (Issue #3)





 
hello，访问演示站点，提示站点不存在？

**Comment by Mengleijin** [comment]
@csx-bill 哦哦，我最近也在看低代码，看文档描述，你这种低代码是前后端都导出源码类型再部署？页面以及页面的接口需要自己手动配置吗？

**Comment by csx-bill** [comment]
不需要导出，直接在线生效，已集成编辑器



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Menglei Jin ***@***.***&gt;
发送时间: 2023年5月29日 19:57
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 站点不存在 (Issue #3)





 
@csx-bill 哦哦，我最近也在看低代码，看文档描述，你这种低代码是前后端都导出源码类型再部署？页面以及页面的接口需要自己手动配置吗？

**Comment by Mengleijin** [comment]
@csx-bill 好的，站点什么时候可以正常啊？想试一试，本地启动报错啊，不知道是不是node版本问题

**Comment by csx-bill** [comment]
周末恢复一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Menglei Jin ***@***.***&gt;
发送时间: 2023年6月1日 12:45
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 站点不存在 (Issue #3)





 
@csx-bill 好的，站点什么时候可以正常啊？想试一试，本地启动报错啊，不知道是不是node版本问题

**Comment by Mengleijin** [comment]
@csx-bill 想问一下，在系统菜单里配置好页面之后，怎么访问配置好的页面呢？它的链接在哪里看啊？

**Comment by csx-bill** [comment]
你配置好，哪个菜单就是哪个菜单，而且 你在配置的时候，也有预览功能呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Spencer ***@***.***&gt;; 
发送时间: 2023年6月8日(星期四) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [csx-bill/quick-boot] 站点不存在 (Issue #3)





 
@csx-bill 想问一下，在系统菜单里配置好页面之后，怎么访问配置好的页面呢？它的链接在哪里看啊？

**Comment by csx-bill** [comment]
已重构，已支持动态路由



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Menglei Jin ***@***.***&gt;
发送时间: 2023年6月8日 14:14
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 站点不存在 (Issue #3)





 
@csx-bill 想问一下，在系统菜单里配置好页面之后，怎么访问配置好的页面呢？它的链接在哪里看啊？

**Comment by laosandegudai** [comment]
可以直接生成一个全版本镜像，发到公共仓库，一键运行。

**Comment by csx-bill** [comment]
正在重构一版



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 老三的古代 ***@***.***&gt;
发送时间: 2023年9月29日 22:03
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 站点不存在 (Issue #3)





 
可以直接生成一个全版本镜像，发到公共仓库，一键运行。
