### ISSUE TITLE
代码跑不起来，可以写点文档吗？

### ISSUE THREAD

**Issue by slotht2026** [csx-bill/quick-boot#4]
![image](https://github.com/csx-bill/quick-boot/assets/42664485/133fde0f-aead-4661-b6e5-ee0e4b85d128)

**Comment by slotht2026** [comment]
代码里是不是缺了东西？红框是我加的
![image](https://github.com/csx-bill/quick-boot/assets/42664485/56931ded-2578-41f7-b72e-60dc5e5c9a4c)

**Comment by csx-bill** [comment]
后端是java


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csx-bill/quick-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 下午4:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [csx-bill/quick-boot] 代码跑不起来，可以写点文档吗？ (Issue #4)





 
代码里是不是缺了东西？红框是我加的

**Comment by slotht2026** [comment]
我用vscode来开发java的，一般项目都可以跑的起来的

**Comment by csx-bill** [comment]
需要安装jdk17



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nnbh2020 ***@***.***&gt;
发送时间: 2023年10月11日 16:54
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 代码跑不起来，可以写点文档吗？ (Issue #4)





 
我用vscode来开发java的，一般项目都可以跑的起来的

**Comment by slotht2026** [comment]
我把我加的那个private String detail; 注释掉之后就报错了，我安装有jdk17
![image](https://github.com/csx-bill/quick-boot/assets/42664485/4ee858e3-40e3-4f6b-8ccd-69be2dde216b)
![image](https://github.com/csx-bill/quick-boot/assets/42664485/b9776a00-044b-4b2e-8b5d-f0147d77086a)

**Comment by slotht2026** [comment]
apijson 的demo 依赖javax.servlet-api
![image](https://github.com/csx-bill/quick-boot/assets/42664485/4cbd4aa2-340e-400b-a352-e396169eeefa)
你的这个项目 import jakarta.servlet.http.HttpSession;
你没有在pom.xml 加它的依赖

**Comment by slotht2026** [comment]
![image](https://github.com/csx-bill/quick-boot/assets/42664485/bda5b9da-3456-4d3d-85b2-d21720308ff8)

**Comment by csx-bill** [comment]
apijson&nbsp; &nbsp;用的springboot3 的，有维护这一个版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csx-bill/quick-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csx-bill/quick-boot] 代码跑不起来，可以写点文档吗？ (Issue #4)

**Comment by csx-bill** [comment]
抽空我补个开发文档


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csx-bill/quick-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csx-bill/quick-boot] 代码跑不起来，可以写点文档吗？ (Issue #4)

**Comment by slotht2026** [comment]
你的OnlineApiController 继承了APIJSONController 
官方的 boot 3 demo 并没有继承APIJSONController
这才是你这代码跑不起来的原因
![image](https://github.com/csx-bill/quick-boot/assets/42664485/3fcdded0-af5e-447b-85e8-b8bb9279419e)

**Comment by csx-bill** [comment]
> 你的OnlineApiController 继承了APIJSONController 官方的 boot 3 demo 并没有继承APIJSONController 这才是你这代码跑不起来的原因 ![图像](https://user-images.githubusercontent.com/42664485/276852843-3fcdded0-af5e-447b-85e8-b8bb9279419e.png)

跟这个没有关系

**Comment by slotht2026** [comment]
我跑官方的boot 3 demo可以跑起来

**Comment by csx-bill** [comment]
> 我跑官方的boot 3 demo可以跑起来

如果像你说那样，我的也就跑不起来了，官方有springboot3的包


https://jitpack.io/#APIJSON/apijson-framework  看这里

![image](https://github.com/csx-bill/quick-boot/assets/31872268/9abdc82b-7036-4f64-a160-7ea47899c3e0)

**Comment by slotht2026** [comment]
Maven setting.xml 配置jitpack.io
https://blog.csdn.net/engchina/article/details/128064038
问题解决了，谢谢
![image](https://github.com/csx-bill/quick-boot/assets/42664485/9c8e43c0-aa90-4109-a9ad-37d3a3ef1636)

**Comment by slotht2026** [comment]
虽然编译通过了，但是还运行不起来
![image](https://github.com/csx-bill/quick-boot/assets/42664485/a1839b0e-ae76-4145-88f9-95f052425063)

**Comment by csx-bill** [comment]
更新最新代码，需要用到 nacos



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nnbh2020 ***@***.***&gt;
发送时间: 2023年10月20日 17:23
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 代码跑不起来，可以写点文档吗？ (Issue #4)





 
虽然编译通过了，但是还运行不起来
