### ISSUE TITLE
我看了你的代码，好像无法兼容别的数据库？apisjon最大的优势就是兼容各种数据库，好像失去了使用apijson的意义

### ISSUE THREAD

**Issue by slotht2026** [csx-bill/quick-boot#5]
![image](https://github.com/csx-bill/quick-boot/assets/42664485/2cc20bd5-a5c9-41bf-bbd3-7cc9231ee189)

**Comment by csx-bill** [comment]
后期调整下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nnbh2020 ***@***.***&gt;
发送时间: 2023年10月12日 11:40
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 我看了你的代码，好像无法兼容别的数据库？apisjon最大的优势就是兼容各种数据库，好像失去了使用apijson的意义 (Issue #5)
