### ISSUE TITLE
更新db

### ISSUE THREAD

**Issue by jzq138156** [csx-bill/quick-boot#8]
作者您好，db有错误，能否上传一份最新的db文件

**Comment by csx-bill** [comment]
正在统一 ui，月底会上传一份



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jzq138156 ***@***.***&gt;
发送时间: 2023年12月24日 21:43
收件人: csx-bill/quick-boot ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [csx-bill/quick-boot] 更新db (Issue #8)





 
作者您好，db有错误，能否上传一份最新的db文件

**Comment by csx-bill** [comment]
已更新
